name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y git zip unzip openjdk-17-jdk python3 python3-pip
          pip install buildozer cython

      - name: Create .buildozer directory
        run: mkdir -p ~/.buildozer

      - name: Build APK
        run: |
          buildozer init || true
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: SogoPOS-APK
          path: bin/*.apk
