name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y python3-pip openjdk-17-jdk unzip git
          pip install --upgrade pip
          pip install buildozer cython virtualenv kivy==2.3.1 kivymd pillow plyer fpdf

      - name: Ensure buildozer.spec exists
        run: |
          if [ ! -f buildozer.spec ]; then
            echo "No buildozer.spec found, creating one..."
            buildozer init
          fi

      - name: Build Android APK
        run: |
          buildozer -v android debug
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SogoPOS-APK
          path: bin/*.apk
